aliyun-oss:
    access-key-secret: yourAccessKeySecret
app-jwt:
    buffer-time: 1d
autocode:
    ai-path: ""
    web: web/src
aws-s3:
    base-url: https://gin.vue.admin
    bucket: xxxxx-10005608
    path-prefix: github.com/icosmos-space/iadmin/server
    region: ap-shanghai
captcha:
    key-long: 6
cloudflare-r2:
    secret-access-key: xxx_secret_key
db-list:
    - alias-name: ""
      config: ""
      db-name: ""
      disable: true
      engine: ""
      log-mode: ""
      log-zap: false
      max-idle-conns: 10
      max-open-conns: 100
      password: ""
      path: ""
      port: ""
      prefix: ""
      singular: false
      type: ""
      username: ""
disk-list:
    - mount-point: /
hua-wei-obs:
    access-key: you-access-key
    bucket: you-bucket
jwt:
    buffer-time: 1d
local:
    path: uploads/file
    store-path: uploads/file
minio:
    bucket-name: yourBucketName
    bucket-url: http://host:9000/yourBucketName
    use-ssl: false
mongo:
    coll: ""
    connect-timeout-ms: 0
    hosts:
        - host: ""
          port: ""
mssql:
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    path: ""
    port: ""
mysql:
    config: ""
    log-mode: ""
    prefix: ""
oracle:
    engine: ""
    log-mode: ""
    log-zap: false
    max-open-conns: 100
    path: ""
    prefix: ""
    singular: false
pgsql:
    db-name: ""
    singular: false
qiniu:
    secret-key: ""
    use-cdn-domains: false
    zone: ZoneHuaDong
redis:
    db: 0
    name: ""
redis-list:
    - addr: 127.0.0.1:6379
      clusteraddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
      db: 0
      name: cache
      password: ""
      usecluster: false
sns-auth:
    feishu:
        auth-url: https://accounts.feishu.cn/open-apis/authen/v1/authorize
        client-id: ""
        client-secret: ""
        enabled: true
        redirect-url: ""
        scopes: ""
        token-url: https://open.feishu.cn/open-apis/authen/v1/oidc/access_token
        user-info-url: https://open.feishu.cn/open-apis/authen/v1/user_info
    github:
        auth-url: https://github.com/login/oauth/authorize
        client-id: ""
        client-secret: ""
        enabled: true
        redirect-url: ""
        scopes: ""
        token-url: https://github.com/login/oauth/access_token
        user-info-url: https://api.github.com/user
    telegram:
        redirect-url: ""
    wechat:
        client-id: ""
        client-secret: ""
        token-url: ""
        user-info-url: ""
sqlite:
    engine: ""
    log-mode: error
    path: ""
system:
    db-type: sqlite
    disable-auto-migrate: false
    iplimit-time: 3600
    router-prefix: ""
    use-redis: false
    use-strict-auth: false
tencent-cos:
    secret-id: your-secret-id
    secret-key: your-secret-key
zap:
    format: console
    level: info
    log-in-console: true
    stacktrace-key: stacktrace
